# Generated by Django 5.0.6 on 2026-06-03 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('plan', models.CharField(choices=[('monthly', 'Mensuel'), ('yearly', 'Annuel')], max_length=10)),
                ('amount', models.PositiveIntegerField()),
                ('fedapay_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('failed', 'Échoué')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('influencer_name', models.CharField(max_length=120)),
                ('influencer_id', models.CharField(blank=True, max_length=120)),
                ('commission_pct', models.PositiveIntegerField(default=25, help_text='Commission versée au promoteur (0 = code sans commission).')),
                ('trial_months', models.PositiveIntegerField(default=3, help_text="Durée d'essai en MOIS (utilisée si « jours d'essai » = 0).")),
                ('trial_days', models.PositiveIntegerField(default=0, help_text="Durée d'essai en JOURS. Si > 0, prioritaire sur les mois (ex : 45 pour 45 jours). Modifiable à tout moment.")),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referred_uid', models.CharField(max_length=128, unique=True)),
                ('referred_email', models.EmailField(blank=True, max_length=254)),
                ('signed_up_at', models.DateTimeField(auto_now_add=True)),
                ('first_year_end', models.DateTimeField()),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='billing.promocode')),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'À verser'), ('paid', 'Versée')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='billing.referral')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='billing.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('contact', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('rejected', 'Rejeté')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
