# Generated by Django 5.0.6 on 2026-06-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_build', models.PositiveIntegerField(default=1, help_text='Dernier build publié (le n° après le + dans pubspec).')),
                ('min_build', models.PositiveIntegerField(default=1, help_text='Build minimum requis : en dessous, la MAJ est OBLIGATOIRE (dialogue bloquant). Mettre = latest_build pour forcer tout le monde.')),
                ('message', models.CharField(blank=True, default='Une nouvelle version de SmartStock est disponible.', max_length=255)),
                ('store_url', models.CharField(blank=True, default='https://smartstock.nouyon.site/telecharger', max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Mise à jour de l'app",
                'verbose_name_plural': "Mise à jour de l'app",
            },
        ),
    ]
