# Generated by Django 5.0.6 on 2026-06-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_appconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrashReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, db_index=True, max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('platform', models.CharField(blank=True, max_length=20)),
                ('app_version', models.CharField(blank=True, max_length=40)),
                ('build_number', models.CharField(blank=True, max_length=20)),
                ('fatal', models.BooleanField(default=False)),
                ('error', models.TextField()),
                ('stack', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Crash / erreur',
                'verbose_name_plural': 'Crashs / erreurs',
                'ordering': ['-created_at'],
            },
        ),
    ]
