# Generated by Django 5.0.6 on 2026-06-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_crashreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text="Interrupteur général de l'IA pour les notifications.")),
                ('provider', models.CharField(choices=[('mistral', 'Mistral'), ('openrouter', 'OpenRouter')], default='mistral', max_length=20)),
                ('model', models.CharField(default='mistral-small-latest', max_length=120)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('temperature', models.FloatField(default=0.9)),
                ('max_tokens', models.PositiveIntegerField(default=120)),
                ('persona', models.TextField(default="Tu es l'assistant de SmartStock, une appli de gestion de stock et de caisse pour commerçants en Afrique de l'Ouest. Tu rédiges de courtes notifications en français, naturelles et chaleureuses mais toujours professionnelles, jamais robotiques. Va droit au but, en 2 phrases maximum, sans jargon technique ni emoji en excès. Les montants sont toujours exprimés en FCFA.")),
                ('ai_morning', models.BooleanField(default=True)),
                ('ai_evening', models.BooleanField(default=True)),
                ('ai_stock', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration IA',
                'verbose_name_plural': 'Configuration IA',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, max_length=128)),
                ('kind', models.CharField(max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('angle', models.CharField(blank=True, max_length=40)),
                ('ai_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Notification envoyée',
                'verbose_name_plural': 'Notifications envoyées',
                'ordering': ['-created_at'],
            },
        ),
    ]
