# Generated by Django 5.0.6 on 2026-06-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_aiconfig_notificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='firebase_uid',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
    ]
