# Generated by Django 5.0.6 on 2026-06-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_promocode_firebase_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='discount_months_left',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='transaction',
            name='discounted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='persona',
            field=models.TextField(default="Tu es l'assistant de Compa, une appli de gestion de stock et de caisse pour commerçants en Afrique de l'Ouest. Tu rédiges de courtes notifications en français, naturelles et chaleureuses mais toujours professionnelles, jamais robotiques. Va droit au but, en 2 phrases maximum, sans jargon technique ni emoji en excès. Les montants sont toujours exprimés en FCFA."),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='message',
            field=models.CharField(blank=True, default='Une nouvelle version de Compa est disponible.', max_length=255),
        ),
    ]
