# Generated by Django 5.0.6 on 2026-07-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_referral_discount_months_left_transaction_discounted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(help_text="UID Firebase OU email de l'utilisateur.", max_length=255)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('sent_count', models.IntegerField(default=0, editable=False)),
                ('resolved_uid', models.CharField(blank=True, editable=False, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Envoi de notification',
                'verbose_name_plural': 'Envois de notifications',
            },
        ),
    ]
